import { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://tadak.io"),
  title: {
    default: "링꾸",
    template: "%s | 링꾸",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="relative mx-auto flex min-h-screen w-full max-w-lg flex-col overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
